### ISSUE TITLE
Orientation supports

### ISSUE THREAD

**Issue by sanghavan** [aspect-apps/react-native-navigation-drawer-extension#30]
I faced an issue which side menu didn't rotate when device rotated.
The main screen already rotated as I enabled it via layout. But side menu isn't.
```
layout: {
     orientation: ['portrait', 'landscape']
}
```
I already tried to pass layout orientation options in show function, but it's not working.

**Comment by lukebrandonfarrell** [comment]
@sanghavan If you want to make a PR for this, you are welcomed. Let me know if you need any internal architecture explaining

**Comment by rodriigovieira** [comment]
This was solved with PR #35. It'll land at npm in the next days.

**Comment by sanghavan** [comment]
Thanks @rodriigovieira, But I confirm that the orientation is still not work on the latest version. When I rotate the device, the function ```Dimensions.addEventListener("change", function (_a) => {})``` executed, but nothing change on the UI.
Also, the drawer didn't open in landscape when calling ```RNNDrawer.showDrawer({...})```

**Comment by lukebrandonfarrell** [comment]
@sanghavan closing this, as we are unable to replicate after @rodriigovieira fix. You can either submit a PR or comment a better process for replication.
